service: maison-inspect 

image: nachiket87/maison-inspect

servers:
  - 159.203.38.9

registry:
  username: nachiket87
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
 clear:
   DB_HOST: 159.203.38.9
 secret:
   - RAILS_MASTER_KEY
   - MAISONINSPECT_DATABASE_PASSWORD

 accessories:
   db:
     image: postgres:14
     host: 159.203.38.9
     port: 5432
     env:
       secret:
         - MAISONINSPECT_DATABASE_PASSWORD
       clear:
         POSTGRES_DB: 'maisoninspect_production'
         POSTGRES_USER: 'maison_inspect'
     files:
       - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
     directories:
       - data:/var/lib/postgresql/data
